version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: easy_maintenance_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: easy_maintenance
      MYSQL_USER: easy_user
      MYSQL_PASSWORD: easy_pass
      TZ: "UTC"
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--explicit_defaults_for_timestamp=1"
    ]
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
